# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        # exclude:
      - id: end-of-file-fixer
        #  exclude:
      - id: check-yaml
        #  files:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

    #    language_version: python3.8
    #    exclude: odoo/external-src/
    #-   id: upstream flake8
    #    args: [--max-line-length=100]
  # black
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        #language_version: python3.6
        #exclude:
        #args: [--fast]

  # isort
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

  #pre-commit-shell
  - repo: git://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint
        args: [--format=json]

  #pre-commit-ruby
  - repo: https://github.com/mattlqx/pre-commit-ruby
    rev: v1.3.1
    hooks:
      - id: rubocop
      - id: foodcritic
      - id: cookstyle
      - id: rspec
      - id: chef-cookbook-version

  #pre-commit prettier
  - repo: https://github.com/prettier/prettier
    rev: "2.0.4" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --write
        language: node
        files: "\\.(\
          css|less|scss\
          |graphql|gql\
          |html\
          |js|jsx\
          |json\
          |md|markdown|mdown|mkdn\
          |mdx\
          |ts|tsx\
          |vue\
          |yaml|yml\
          )$"
