# global settings
name: smussie
github_username: smussie
title: "My github page"
description: >- #this means ignore newlines until "baseurl:"
  My adventures in coding
#permalink: "/:title"
permalink: pretty
#theme: jekyll-theme-hacker
url: "https://smussie.github.io"
#relative_permalinks: false

# Build settings
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "Rakefile", "README.md", "Jekyll guide.md"]
markdown: kramdown
#plugins:
#  - jekyll-avatar
#  - jekyll-redirect-form
#  - jekyll-seo-tag
#  - jekyll-coffescript
#  - jekyll-sitemap
#  - jekyll-octicons
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  toc_levels: 1..3

collections:
  pages:
    output: true
    permalink: /:path
#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#      type: "posts" # previously `post` in Jekyll 2.2. #pages, posts, drafts as type is optional the value for path must be specified
#    values:
#      layout: "default" #eg my-site
#  -
#    scope:
#      path: "projects" #any docs in the project/ folder will use the project layout
#      type: "pages" # previously `page` in Jekyll 2.2.
#    values:
#      layout: "project" # overrides previous default layout
#      author: "Mr. Hyde" #the also get page.author liquid variable to Mr. Hyde

#Build settings
#markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-theme-hacker
#https://jekyllrb.com/docs/configuration/
